### ISSUE TITLE
Outdated last run for all models

### ISSUE THREAD

**Issue by vtoupet** [OpenMeteoData/meteo-france-models#13]
Hi,

It looks like there is a problem with the data on https://mf-models-on-aws.org. The last fetched run is from yesterday and since then nothing comes in. Could you have a look at the cron job (or whatever scheduler that periodically fetches grib2 files from Météo France servers?

I have checked the availability of the GRIB2 files on Meteo France servers and there does not seem to have any problem on their side.

Again, I would like to propose my service to maintain the application in charge of fetching data. @nbald Do not hesitate to let me know if that would be possible.

Thanks,
Vincent

**Comment by nbald** [comment]
There was an issue with the proxy servers. It should be fixed by now.

**Comment by vtoupet** [comment]
Thanks @nbald for your fast reply and reactivity to fix the issue.

Any specific reason why the source code responsible for this service is not open sourced?

**Comment by nbald** [comment]
I have no plan to open-source this specific code. I want to keep some of the magic for myself.

**Comment by blaza1** [comment]
Thanks for your quick turnaround on the issue :-)

We are still missing the 00 run for yesterday https://mf-models-on-aws.org/#arome-france-hd/v1/2023-01-10/ and https://mf-models-on-aws.org/#arome-france/v1/2023-01-10/. Is there a plan to add this run to AWS ?

I've checked and the run has been succesfully added for today's 00 model.
